export const countries = [
  { code: "🇦🇷", name: "Argentina", dialCode: "+54" },
  { code: "🇧🇴", name: "Bolivia", dialCode: "+591" },
  { code: "🇧🇷", name: "Brasil", dialCode: "+55" },
  { code: "🇨🇱", name: "Chile", dialCode: "+56" },
  { code: "🇨🇴", name: "Colombia", dialCode: "+57" },
  { code: "🇨🇷", name: "Costa Rica", dialCode: "+506" },
  { code: "🇨🇺", name: "Cuba", dialCode: "+53" },
  { code: "🇩🇴", name: "República Dominicana", dialCode: "+1" },
  { code: "🇪🇨", name: "Ecuador", dialCode: "+593" },
  { code: "🇸🇻", name: "El Salvador", dialCode: "+503" },
  { code: "🇬🇹", name: "Guatemala", dialCode: "+502" },
  { code: "🇭🇳", name: "Honduras", dialCode: "+504" },
  { code: "🇲🇽", name: "México", dialCode: "+52" },
  { code: "🇳🇮", name: "Nicaragua", dialCode: "+505" },
  { code: "🇵🇦", name: "Panamá", dialCode: "+507" },
  { code: "🇵🇾", name: "Paraguay", dialCode: "+595" },
  { code: "🇵🇪", name: "Perú", dialCode: "+51" },
  { code: "🇵🇷", name: "Puerto Rico", dialCode: "+1" },
  { code: "🇪🇸", name: "España", dialCode: "+34" },
  { code: "🇺🇾", name: "Uruguay", dialCode: "+598" },
  { code: "🇻🇪", name: "Venezuela", dialCode: "+58" },
  { code: "🇺🇸", name: "Estados Unidos", dialCode: "+1" },
  { code: "🇬🇧", name: "Reino Unido", dialCode: "+44" },
  { code: "🇨🇦", name: "Canadá", dialCode: "+1" },
  { code: "🇮🇳", name: "India", dialCode: "+91" },
  { code: "🇦🇺", name: "Australia", dialCode: "+61" },
  { code: "🇩🇪", name: "Alemania", dialCode: "+49" },
  { code: "🇫🇷", name: "Francia", dialCode: "+33" },
  { code: "🇮🇹", name: "Italia", dialCode: "+39" },
  { code: "🇯🇵", name: "Japón", dialCode: "+81" },
  { code: "🇨🇳", name: "China", dialCode: "+86" },
]
